// src/admin/programmesPageTypes.ts

export interface ProgrammesPageData {
  id: number;
  created_at: string;
  text_en: string | null;
  text_es: string | null;
  text_ru: string | null;
  title_en: string | null;
  title_es: string | null;
  title_ru: string | null;
  subs_text_en: string | null;
  subs_text_es: string | null;
  subs_text_ru: string | null;
  subs_title_en: string | null;
  subs_title_es: string | null;
  subs_title_ru: string | null;
  text_two_en: string | null;
  text_two_es: string | null;
  text_two_ru: string | null;
  text_two_image: string | null;
  card_one_img: string | null;
  card_two_img: string | null;
  card_three_img: string | null;
  card_four_img: string | null;
  card_one_text_en: string | null;
  card_one_text_es: string | null;
  card_one_text_ru: string | null;
  card_two_text_en: string | null;
  card_two_text_es: string | null;
  card_two_text_ru: string | null;
  card_three_text_en: string | null;
  card_three_text_es: string | null;
  card_three_text_ru: string | null;
  card_four_text_en: string | null;
  card_four_text_es: string | null;
  card_four_text_ru: string | null;
  fourCards_title_en: string | null;
  fourCards_title_es: string | null;
  fourCards_title_ru: string | null;
}

export interface ProgrammesPageFormData {
  text_en: string | null;
  text_es: string | null;
  text_ru: string | null;
  title_en: string | null;
  title_es: string | null;
  title_ru: string | null;
  subs_text_en: string | null;
  subs_text_es: string | null;
  subs_text_ru: string | null;
  subs_title_en: string | null;
  subs_title_es: string | null;
  subs_title_ru: string | null;
  text_two_en: string | null;
  text_two_es: string | null;
  text_two_ru: string | null;
  text_two_image: string | null;
  card_one_img: string | null;
  card_two_img: string | null;
  card_three_img: string | null;
  card_four_img: string | null;
  card_one_text_en: string | null;
  card_one_text_es: string | null;
  card_one_text_ru: string | null;
  card_two_text_en: string | null;
  card_two_text_es: string | null;
  card_two_text_ru: string | null;
  card_three_text_en: string | null;
  card_three_text_es: string | null;
  card_three_text_ru: string | null;
  card_four_text_en: string | null;
  card_four_text_es: string | null;
  card_four_text_ru: string | null;
  fourCards_title_en: string | null;
  fourCards_title_es: string | null;
  fourCards_title_ru: string | null;
}